const texts = {
  en: {
    app_title: "Reading Goals",
    app_desc: "With this application it is easy to keep track of your reading goals.",
    readings: "Readings",
    books: "Books",
    login: "Login",
    logout: "Logout",
    register: "Register",
    new_book: "New Book",
    showing: "Showing",
    books_in_db: "books in the database.",
    title: "Title",
    author: "Author",
    ISBN: "ISBN",
    description: "Description",
    pages: "Pages",
    read_this: "Read this",
    delete: "Delete",
    search: "Search...",
    save: "Save",
    book_details: "Book Details",
    upload_image: "Upload image",
    cancel: "Cancel",
    use_image: "Use image",
    choose_images: "Choose image",
    image_label: "Max file size: {0}mb, accepted: {1}",
    current_page: "Current page",
    time_spent: "Time spent",
    rating: "Rating",
    comments: "Comments",
    last_update: "Last update",
    reading_details: "Reading Details",
    readings_in_db: "readings in the database.",
    user_name: "Name *",
    user_email: "Email Address *",
    user_pw_cur: "Current Password *",
    user_pw_new: "New Password",
    user_password: "Password *",
    not_found: "Not Found",
    start_reading: "Start reading",
    image_selected: "Image selected, please save.",
    book_saved: "Book saved successfully.",
    book_deleted: "Book deleted successfully.",
    book_already_deleted: "This book has already been deleted.",
    access_denied: "Access denied.",
    bad_request: "Bad request.",
    reading_already_deleted: "This reading has already been deleted.",
    remember_me: "Remember me",
    login_title: "Please login",
    reading_added: "Book added to the reading list.",
    reading_deleted: "Book deleted from the reading list.",
    changes_saved: "Changes saved successfully.",
    finnish_lang: "FI - Finnish",
    english_lang: "EN - English",
  },
  fi: {
    app_title: "Lukutavoitteet",
    app_desc: "Tällä sovelluksella on helppo seurata lukutavoitteitasi.",
    readings: "Luettavat",
    books: "Kirjat",
    login: "Kirjaudu sisään",
    logout: "Kirjaudu ulos",
    register: "Uusi käyttäjä",
    new_book: "Uusi kirja",
    showing: "Näytetään",
    books_in_db: "kirjaa tietokannassa.",
    title: "Kirjan nimi",
    author: "Tekijä",
    ISBN: "ISBN",
    description: "Kuvaus",
    pages: "Sivuja",
    read_this: "Lue tämä",
    delete: "Poista",
    search: "Haku...",
    save: "Talleta",
    book_details: "Kirjan tiedot",
    upload_image: "Lataa kuva",
    cancel: "Peruuta",
    use_image: "Käytä kuvaa",
    choose_images: "Valitse kuva",
    image_label: "Max tiedoston koko: {0}mb, hyväksytään: {1}",
    current_page: "Nykyinen sivu",
    time_spent: "Luetut minuutit",
    rating: "Pisteet",
    comments: "Kommentit",
    last_update: "Viimeksi päivitetty",
    reading_details: "Lukemisen tiedot",
    readings_in_db: "luettavaa tietokannassa.",
    user_name: "Nimi *",
    user_email: "Sähköposti *",
    user_pw_cur: "Nykyinen salasana *",
    user_pw_new: "Uusi salasana",
    user_password: "Salasana *",
    not_found: "Sivua ei löydy",
    start_reading: "Aloita lukeminen",
    image_selected: "Kuva valittu, ole hyvä ja tallenna.",
    book_saved: "Kirja talletettu.",
    book_deleted: "Kirja poistettu.",
    book_already_deleted: "Tämä kirja on jo poistettu.",
    access_denied: "Pääsy evätty.",
    bad_request: "Virheellinen pyyntö.",
    reading_already_deleted: "Tämä luettava on jo poistettu.",
    remember_me: "Muista minut",
    login_title: "Sisäänkirjautuminen",
    reading_added: "Kirja lisätty luettavien listalle.",
    reading_deleted: "Kirja poistettu luettavien listalta.",
    changes_saved: "Muutokset talletettu.",
    finnish_lang: "FI - Suomi",
    english_lang: "EN - Englanti",
  }
}

export default texts;